#!/usr/bin/env python3
"""Write MANIFEST.md: who showed up, with what, and what the data covers.

Catalog comes from the published all.csv files; raw-waveform counts come from
the database, so years whose release set has not been imported still appear in
the catalog with no waveform figures.

    python3 scripts/make_manifest.py summit2025/all.csv summit2026/all.csv \
        --database tbacss.db --output MANIFEST.md
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tbacss.summit import read_summary_csv  # noqa: E402

HOSTS = {
    ".22LR-BA": '16.5" bolt-action .22LR, Volquartsen Summit, CCI Std Vel',
    ".22LR-PS": ".22LR pistol, Sig P322, CCI Std Vel",
    ".22LR-Integral-SA": "Innovative Arms integrally-suppressed .22 rifle",
    "5.56-16AR": '16" DD AR-15, LC M193 55gr',
    "5.56-105AR": '10.5" 5.56 AR, LC M193',
    "5.56-11.5AR": 'Allen Engineering 11.5" AR',
    "5.56-12.5AR": 'Allen Engineering 12.5" AR',
    "5.56-14.5AR": 'Allen Engineering 14.5" AR',
    "5.56-AE12.5AR": 'Allen Engineering 12.5" AR',
    "5.56-AE18AR": 'Allen Engineering 18" AR',
    "5.56-MK12AR": "B&T MK12",
    "13.7-5.56-Infidel": '13.7" 5.56 AR (Noveske Infidel)',
    "6CM-BA": "6mm Creedmoor bolt action",
    "6.5GREN-20AR": 'W.T.F. 20" 6.5 Grendel AR',
    ".300WM-BA": '26" Savage 110, Federal 150gr SP .300 Win Mag',
    ".300BO-16AR-SUB": '16" DD .300BO AR, 220gr subsonic Ammo Inc Stelth',
    ".300BO-16BA": '16" bolt action .300BO, 220gr subsonic Ammo Inc Stelth',
    ".300BO-RAT-110": "Sig Rattler, 110gr Barnes",
    ".300BO-RAT-220": "Sig Rattler, 220gr subsonic",
    ".300BO-SUBS-Integral": "B&T integrally-suppressed rifle",
    ".308-20BA": '20" AI-AX, M118LR',
    ".308-24BA": 'B&T 24" .308, M118LR',
    ".338LM-26BA": '26" Barrett MRAD, Hornady 285gr ELD',
    ".338LM-SAKO": '27" Sako TRG M10, 250gr Sako .338 Lapua',
    ".50BW-SUB-10.5AR": '10.5" AR, subsonic .50 Beowulf',
    "9mm-PS": "Canik METE SFX pistol, Ammo Inc Stelth 165gr",
    "9mm-19X": "Integral Glock 19X, Ammo Inc Stelth 165gr",
    "9mm-5AR": '5" AR9',
    "9mm-EI-PCC": '8.5" AR9 (Elite Iron), Stelth 165gr',
    "10mm-SUB-Stribog": "Grand Power Stribog, subsonic 10mm",
    "Berretta-32Auto": "Beretta .32 Auto pistol",
}


def load_waveform_stats(db_path: Path) -> dict[int, dict]:
    if not db_path.exists():
        return {}
    connection = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row
    rows = connection.execute(
        """SELECT d.year,
                  COUNT(DISTINCT r.id) AS runs,
                  COUNT(w.id)          AS waveforms,
                  SUM(w.n_samples)     AS samples
           FROM dataset d
           JOIN test_run r ON r.dataset_id = d.id
           LEFT JOIN waveform w ON w.test_run_id = r.id
           GROUP BY d.year"""
    ).fetchall()
    connection.close()
    return {row["year"]: dict(row) for row in rows}


def year_of(path: Path) -> int:
    match = re.search(r"(20\d{2})", str(path))
    if not match:
        raise SystemExit(f"cannot infer a year from {path}")
    return int(match.group(1))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csvs", nargs="+", type=Path)
    parser.add_argument("--database", type=Path, default=Path("tbacss.db"))
    parser.add_argument("--output", type=Path, default=Path("MANIFEST.md"))
    args = parser.parse_args()

    stats = load_waveform_stats(args.database)
    years = {year_of(path): read_summary_csv(path) for path in args.csvs}
    ordered = sorted(years, reverse=True)

    # manufacturer -> suppressor -> {year: set(caliber)}
    catalog: dict[str, dict[str, dict[int, set[str]]]] = defaultdict(
        lambda: defaultdict(lambda: defaultdict(set))
    )
    for year, rows in years.items():
        for row in rows:
            catalog[row.manufacturer][row.suppressor][year].add(row.caliber)

    out: list[str] = ["# Silencer Summit data manifest", ""]
    out.append(
        "Generated by `scripts/make_manifest.py` from the published `all.csv` "
        "files. Counts of raw waveforms come from the SQLite build."
    )
    out.append("")

    out.append("## Coverage by year")
    out.append("")
    out.append("| year | days | runs | makers | models | calibers | hosts | waveforms | samples |")
    out.append("| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for year in ordered:
        rows = years[year]
        wave = stats.get(year, {})
        models = {(r.manufacturer, r.suppressor) for r in rows}
        out.append(
            f"| {year} | {len({r.event_label for r in rows})} | {len(rows)} "
            f"| {len({r.manufacturer for r in rows})} | {len(models)} "
            f"| {len({r.caliber for r in rows})} | {len({r.cartridge for r in rows})} "
            f"| {wave.get('waveforms') or '--'} "
            f"| {format(wave['samples'], ',') if wave.get('samples') else '--'} |"
        )
    out.append("")

    out.append("## Suppressor calibers tested")
    out.append("")
    out.append("Runs per suppressor bore diameter. A can is often run on a")
    out.append("larger-bore host, so these do not match the cartridge counts below.")
    out.append("")
    header = " | ".join(str(year) for year in ordered)
    out.append(f"| caliber | {header} |")
    out.append("| --- |" + " ---: |" * len(ordered))
    calibers = {r.caliber for rows in years.values() for r in rows}
    for caliber in sorted(calibers, key=lambda c: -sum(
        sum(1 for r in years[y] if r.caliber == c) for y in ordered
    )):
        counts = [
            str(sum(1 for r in years[year] if r.caliber == caliber) or "--")
            for year in ordered
        ]
        out.append(f"| {caliber} | " + " | ".join(counts) + " |")
    out.append("")

    out.append("## Host and cartridge codes")
    out.append("")
    out.append(f"| code | host / ammunition | {header} |")
    out.append("| --- | --- |" + " ---: |" * len(ordered))
    cartridges = {r.cartridge for rows in years.values() for r in rows}
    for cartridge in sorted(cartridges, key=lambda c: -sum(
        sum(1 for r in years[y] if r.cartridge == c) for y in ordered
    )):
        counts = [
            str(sum(1 for r in years[year] if r.cartridge == cartridge) or "--")
            for year in ordered
        ]
        description = HOSTS.get(cartridge, "_not described in the report_")
        out.append(f"| `{cartridge}` | {description} | " + " | ".join(counts) + " |")
    out.append("")

    out.append("## Manufacturers and models")
    out.append("")
    out.append(
        "Year columns mark which summits a model appears in; the caliber is the "
        "suppressor bore as entered by the maker."
    )
    out.append("")
    for manufacturer in sorted(catalog, key=str.lower):
        models = catalog[manufacturer]
        seen = sorted({year for m in models.values() for year in m}, reverse=True)
        out.append(
            f"### {manufacturer} "
            f"<sub>{len(models)} model{'s' if len(models) != 1 else ''} "
            f"| {', '.join(str(y) for y in seen)}</sub>"
        )
        out.append("")
        out.append(f"| model | caliber | {header} |")
        out.append("| --- | --- |" + " ---: |" * len(ordered))
        for model in sorted(models, key=str.lower):
            per_year = models[model]
            bores = sorted({c for cals in per_year.values() for c in cals})
            marks = [
                str(len(per_year[year])) if year in per_year else "--"
                for year in ordered
            ]
            out.append(
                f"| {model} | {', '.join(bores)} | " + " | ".join(marks) + " |"
            )
        out.append("")

    args.output.write_text("\n".join(out) + "\n")
    print(f"wrote {args.output} ({len(catalog)} manufacturers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
