#!/usr/bin/env python3
"""Write PROVENANCE.md: where every input came from, and its hash and size.

Archive figures come from the database, which records them as the tarball is
streamed, so they describe the bytes that were actually parsed rather than
whatever is on disk now. The summary tables are hashed here directly.

    python3 scripts/make_provenance.py tbacss.db --output PROVENANCE.md
"""

from __future__ import annotations

import argparse
import hashlib
import sqlite3
from pathlib import Path

# Where each release archive was fetched from. TBAC hosts 2023 itself and puts
# the later years on Dropbox behind capability links, which is why these are
# recorded rather than assumed -- see the note in the generated file.
ARCHIVE_URLS = {
    2023: "https://thunderbeastarms.com/sound/summit2023/2023_SUMMIT_RELEASE_SET.tar.gz",
    2024: (
        "https://www.dropbox.com/scl/fi/x0rzms56e52nd2bpy53a8/"
        "2024_SUMMIT_RELEASE_SET.tar.gz?rlkey=3jjtikha3tkvrejcawju5nhz3&dl=1"
    ),
    2025: (
        "https://www.dropbox.com/scl/fi/yxxu6dgejp2e2g18wyuvo/"
        "2025_SUMMIT_RELEASE_SET.tar.gz?rlkey=n98408fdjv54rji0m4ulxxuv3&dl=1"
    ),
    2026: (
        "https://www.dropbox.com/scl/fi/j91yeyrv1lwcpzoxmdkqp/"
        "2026_SUMMIT_RELEASE_SET.tar.gz?rlkey=99bnrfz6av31gvet5ix780apc&dl=1"
    ),
}
SUMMARY_URL = "https://thunderbeastarms.com/sound/summit{year}/HTML/all.csv"


def sha256(path: Path) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
            size += len(chunk)
    return digest.hexdigest(), size


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("database", nargs="?", default="tbacss.db")
    parser.add_argument("--output", type=Path, default=Path("PROVENANCE.md"))
    args = parser.parse_args()

    root = Path(args.database).resolve().parent
    connection = sqlite3.connect(f"file:{args.database}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row
    datasets = connection.execute(
        """SELECT year, report_url, archive_name, archive_bytes, archive_sha256,
                  archive_url, imported_at
           FROM dataset ORDER BY year"""
    ).fetchall()

    out = [
        "# Provenance",
        "",
        "Every input, where it came from, and what it hashed to. Generated by",
        "`scripts/make_provenance.py` from the database, which digests each",
        "archive as it streams it, so these describe the bytes that were parsed.",
        "",
        "See [ATTRIBUTION.md](ATTRIBUTION.md) for the terms this data is used under.",
        "",
        "## Release archives",
        "",
    ]

    for row in datasets:
        year = row["year"]
        out.append(f"### {year}")
        out.append("")
        if not row["archive_name"]:
            out += [
                "Not released yet. The report page still shows `TBD` where the",
                "download link goes, so only the published table is imported.",
                "",
                f"* report: {row['report_url']}",
                f"* table: {SUMMARY_URL.format(year=year)}",
                "",
            ]
            continue
        url = row["archive_url"] or ARCHIVE_URLS.get(year) or "_not recorded_"
        size = row["archive_bytes"]
        out += [
            f"* file: `{row['archive_name']}`",
            f"* url: {url}",
            f"* size: {size:,} bytes ({size / 1e9:.2f} GB)" if size else "* size: _not recorded_",
            f"* sha256: `{row['archive_sha256'] or 'not recorded'}`",
            f"* report: {row['report_url']}",
            f"* imported: {row['imported_at']}",
            "",
        ]

    out += [
        "## Summary tables",
        "",
        "Small enough to track in git, so these are the copies in this repo.",
        "",
        "| year | file | bytes | sha256 |",
        "| ---: | --- | ---: | --- |",
    ]
    for row in datasets:
        year = row["year"]
        for name in (f"summit{year}/all.csv", f"summit{year}/physical-specs.csv"):
            path = root / name
            if not path.exists():
                continue
            digest, size = sha256(path)
            out.append(f"| {year} | `{name}` | {size:,} | `{digest}` |")
    out.append("")

    out += [
        "## Verifying a copy",
        "",
        "```",
        "sha256sum -c <<'EOF'",
    ]
    for row in datasets:
        if row["archive_sha256"] and row["archive_name"]:
            out.append(f"{row['archive_sha256']}  {row['archive_name']}")
    out += ["EOF", "```", ""]

    out += [
        "## Hosting",
        "",
        "2023 is served by TBAC directly. 2024 onwards are Dropbox capability",
        "links: the `rlkey` and `st` query parameters are tokens, the `st` one",
        "is short-lived, and neither URL is a durable citation. The hashes above",
        "are what actually pins these files.",
        "",
        "**Planned:** rehost the archives on static storage under our own",
        "control, keyed by the sha256 above so a mirrored copy is verifiable",
        "against this file. Until then `scripts/fetch_sources.sh --archives`",
        "carries working links, and they will need refreshing when Dropbox",
        "rotates the tokens.",
        "",
        "Also worth noting: `thunderbeastarms.com` serves only its leaf",
        "certificate and omits the Sectigo intermediate, so plain `curl` fails",
        "where a browser succeeds. `scripts/fetch_sources.sh` fetches the",
        "intermediate from the certificate's AIA URL and builds a bundle.",
        "",
    ]

    args.output.write_text("\n".join(out))
    print(f"wrote {args.output} covering {len(datasets)} years")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
